name: Build and push miultiarch docker image

on: 
  push:
    branches: ["*"]
  pull_request: 
    branches: ["*"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to dockerhub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Dockerfile image for amd64
        run: docker build --platform=linux/amd64 -t rovniy0/program:amd64 --push .

      - name: Build Dockerfile image for arm64
        run: docker build --platform=linux/arm64 -t rovniy0/program:arm64 --push .
      
      - name: Create manifest
        run: docker manifest create rovniy0/program --amend rovniy0/program:amd64 --amend rovniy0/newprogram:arm64

      - name: Push manifest to docker hub
        run: docker manifest push rovniy0/program

